djcrm/urls.py
from django.contrib import admin
from django.urls import path,include 
from leads.views import landing_page ,landingpageview,SignupView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('leads/',include('leads.urls',namespace="leads")),
    path('agents/',include('agents.urls',namespace="agents")),
    path('',landingpageview.as_view(),name="landing_page"),
    path('reset-password/',PasswordResetView.as_view(),name="reset-password"),
    path('password-reset-done/',PasswordResetDoneView.as_view(),name="password_reset_done"),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(),name="password_reset_complete"),
    path('password-reset-confirm/<uidb64>/<token>/',PasswordResetConfirmView.as_view(),name="password-reset-confirm"),
    path('login/',LoginView.as_view(),name="login"),
    path('logout/',LogoutView.as_view(),name="logout"),
    path('signup/' , SignupView.as_view(),name="signup")
    
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path

from .views import (LeadListView,LeadDetailView,LeadCreateView,
                    LeadUpdateView,DeleteView,AssignAgentView,
                    CategoryListView,CategoryDetailView,LeadCategoryUpdateView)

app_name="leads"

urlpatterns=[
    path('',LeadListView.as_view(),name="lead_list"),
    path('<int:pk>/',LeadDetailView.as_view(),name="lead_view"),
    path('<int:pk>/update/',LeadUpdateView.as_view(),name="lead_update"),
    path('<int:pk>/delete/',DeleteView.as_view(),name="lead_delete"),
    path('create/',LeadCreateView.as_view(),name="lead_create"),
    path('<int:pk>/assign-agent/',AssignAgentView.as_view(),name="assign_agent"),
    path('<int:pk>/category/',LeadCategoryUpdateView.as_view(),name="lead_category_update"),
    path('categories/',CategoryListView.as_view(),name="category_list"),
    path('categories/<int:pk>/',CategoryDetailView.as_view(),name="category_detail")
    

]

leads/models.py
from django.db import models
# from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser

from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.

# User=get_user_model()

class User(AbstractUser):
    is_organisor=models.BooleanField(default=True)
    is_agent=models.BooleanField(default=False)

class UserProfile(models.Model):

    user=models.OneToOneField(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Lead(models.Model):

    # values stored in (database ,diplay value) , does not restrict the value can also stroe a  different value


    # SOURCE_CHOICES=(
    #     ('youtube','youtube'),
    #     ('google','google'),
    #     ('newsletter','newsletter')

    # )

    first_name = models.CharField(max_length=20)
    last_name=models.CharField(max_length=20)
    age=models.IntegerField(default=0)
    agent=models.ForeignKey("Agent",null=True,blank=True, on_delete=models.SET_NULL)
    organisation=models.ForeignKey(UserProfile,on_delete=models.CASCADE)
    category=models.ForeignKey("Category" ,related_name="leads",null=True,blank=True,on_delete=models.SET_NULL)
    
    description=models.TextField()
    date_added=models.DateTimeField(auto_now_add=True)
    phone_number=models.CharField(max_length=20)
    email=models.EmailField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    # agent can be put in quotation and then it would not benecessary to be put in top , 
    # if you just write agent then you would hgave to put theagent calss on the top
    
    # phoned=models.BooleanField(default=False)
    # source=models.CharField(choices=SOURCE_CHOICES)

    # profile_pic=models.ImageField(blank=True,null=True)

    # special_file=models.FileField()

class Agent(models.Model):

    # user=models.ForeignKey(User,on_delete=models.CASCADE)

    user=models.OneToOneField(User,on_delete=models.CASCADE)
    organisation=models.ForeignKey(UserProfile,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.email
    
  
class Category(models.Model):
    name=models.CharField(max_length=30)
    organisation=models.ForeignKey(UserProfile,on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
    



@receiver(post_save, sender=User)
def post_user_created_signal(sender, instance, created, **kwargs):
    if created:
        
        UserProfile.objects.create(user=instance)
    

leads/forms.py
from django import forms
from .models import Lead ,Agent
from django.contrib.auth.forms import UserCreationForm , UsernameField
from django.contrib.auth import get_user_model

User=get_user_model()


class LeadModelForm(forms.ModelForm):
    class Meta:
        model= Lead 
        fields=(
            'first_name',
            'last_name',
            'age',
            'agent',
                
            'description',
            
            'phone_number',
            'email',
        )





class LeadForm(forms.Form):
    first_name=forms.CharField()
    last_name=forms.CharField()
    age=forms.IntegerField(min_value=0)


class CustomUserCreation(UserCreationForm):
    class Meta:
        model=User
        fields={"username",}
        field_classes={'username' : UsernameField}

class AssignAgentForm(forms.Form):
    agent=forms.ModelChoiceField(queryset=Agent.objects.none())

    def __init__(self,*args,**kwargs):
        
        request=kwargs.pop("request")
        agents=Agent.objects.filter(organisation=request.user.userprofile)
        super(AssignAgentForm,self).__init__(*args,**kwargs)
        self.fields["agent"].queryset=agents

        
class LeadCategoryUpdateForm(forms.ModelForm):
    class Meta:
        model=Lead
        fields=(
            'category',

        )

leads/views.py
from django.shortcuts import render,redirect,reverse
from django.http import HttpResponse
from django.views import generic  
from .models import Lead,Agent,Category
from .forms import LeadForm,LeadModelForm,CustomUserCreation,AssignAgentForm,LeadCategoryUpdateForm
from django.core.mail import send_mail
from django.contrib.auth.mixins import LoginRequiredMixin
from agents.mixins import organisorandLoginRequiredMixin
# from django.contrib.auth.forms import UserCreationForm

# Create your views here.
#CRUD-- create ,retrive,update,delete +list

class SignupView(generic.CreateView):
    template_name="registration/signup.html"
    form_class=CustomUserCreation

    def get_success_url(self):
        return reverse("login")





class  landingpageview (generic.TemplateView):
    template_name="leads/landing_page.html"


def landing_page(request):

    return render(request,"leads/landing_page.html")

class LeadListView(LoginRequiredMixin , generic.ListView):
    template_name="leads/lead_list.html"
    context_object_name="lead"
    
    def get_queryset(self):
        user=self.request.user

        if user.is_organisor:
            queryset=Lead.objects.filter(organisation=user.userprofile , agent__isnull=False)

        else:
            queryset=Lead.objects.filter(organisation=user.agent.organisation , agent__isnull=False)

            #filter for the agent that is logged in
            queryset=queryset.filter(agent__user=user)

        return queryset
    
    def get_context_data(self,**kwargs):
        user=self.request.user
        context=super(LeadListView,self).get_context_data(**kwargs)
        if user.is_organisor:
            queryset=Lead.objects.filter(
                organisation=user.userprofile,
                agent__isnull=True
            )
            context.update({
                "unassigned_lead": queryset
            })
       
        return context

    #by default object_list is assigned to the queryset name
    


def lead_list(request):
    lead=Lead.objects.all()

    context={"lead":lead}
    # return HttpResponse("hello world")
    return render(request,"leads/lead_list.html",context)


class LeadDetailView(LoginRequiredMixin ,generic.DetailView):
    template_name="leads/lead_details.html"
    context_object_name="leads"

    def get_queryset(self):
        user=self.request.user

        if user.is_organisor:
            queryset=Lead.objects.filter(organisation=user.userprofile)

        elif user.is_agent:
            queryset=Lead.objects.filter(organisation=user.agent.organisation)

            #filter for the agent that is logged in
            queryset=queryset.filter(agent__user=user)

        return queryset

def lead_view(request,pk):
    print(pk)
    lead=Lead.objects.get(id=pk)
    context={
        "leads":lead
    }
    # return HttpResponse(f"here's the detail view {lead}")
    return render(request,"leads/lead_details.html",context)

class LeadCreateView(organisorandLoginRequiredMixin ,generic.CreateView):
    template_name="leads/lead_create.html"
    form_class=LeadModelForm

    def get_success_url(self):
        # return redirect("/leads")
        return reverse("leads:lead_list")
    
    def form_valid(self,form):

        lead=form.save(commit=False)
        lead.organisation=self.request.user.userprofile
        lead.save()

        # TODO send email
        send_mail(subject="a new lead has been created" , 
                  message="go to the site to see the neww lead",
                  from_email="test@test.com",
                  recipient_list=["test2@test.com"])

        return super(LeadCreateView,self).form_valid(form)

    



def lead_create(request):
    form=LeadModelForm()
    
    if request.method=="POST":
        print("recieving post request")
        form=LeadModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/leads")

    context={
        "form":form
    }
    return render(request,"leads/lead_create.html",context)

class LeadUpdateView(organisorandLoginRequiredMixin ,generic.UpdateView):
    template_name="leads/lead_update.html"
    form_class=LeadModelForm
    
    
    context_object_name="lead"

    def get_queryset(self):
        user=self.request.user


        return Lead.objects.filter(organisation=user.userprofile)

    def get_success_url(self):
        return reverse("leads:lead_list")



def lead_update(request,pk):
    
    lead=Lead.objects.get(id=pk)
    form=LeadModelForm(instance=lead)
    if request.method=="POST":
        
       
        form=LeadModelForm(request.POST,instance=lead)
        if form.is_valid():
            form.save()
            return redirect("/leads")

            
            
            
    
    context={
        'lead':lead,
        'form':form
        }
    
    return render(request,"leads/lead_update.html",context)


class DeleteView(organisorandLoginRequiredMixin ,generic.DeleteView):
    template_name="leads/lead_delete.html"
    
    
    def get_success_url(self):
            return reverse("leads:lead_list") 
    
    def get_queryset(self):
        user=self.request.user


        return Lead.objects.filter(organisation=user.userprofile)

def lead_delete(request,pk):
    lead=Lead.objects.get(id=pk)
    lead.delete()
    return redirect("/leads")



class AssignAgentView(organisorandLoginRequiredMixin, generic.FormView):
    template_name="leads/assign_agent.html"
    form_class=AssignAgentForm

    def get_form_kwargs(self,**kwargs):
        kwargs=super(AssignAgentView,self).get_form_kwargs(**kwargs)
        kwargs.update({
            "request":self.request
        })
        return kwargs

    def get_success_url(self):
        return reverse("leads:lead_list")

    def form_valid(self,form):
        agent=form.cleaned_data["agent"]
        lead=Lead.objects.get(id=self.kwargs["pk"])
        lead.agent=agent
        lead.save()
        return super(AssignAgentView,self).form_valid(form)



class CategoryListView(LoginRequiredMixin,generic.ListView):
    template_name="leads/category_list.html"
    context_object_name="category_list"

    def get_context_data(self, **kwargs):
        context= super(CategoryListView,self).get_context_data(**kwargs)
        user=self.request.user

        if user.is_organisor:
            queryset=Lead.objects.filter(organisation=user.userprofile )

        else:
            queryset=Lead.objects.filter(organisation=user.agent.organisation )

        context.update({
            "unassigned_lead_count":queryset.filter(category__isnull=True).count()
        })

        return context


    def get_queryset(self):
        user=self.request.user

        if user.is_organisor:
            queryset=Category.objects.filter(organisation=user.userprofile )

        else:
            queryset=Category.objects.filter(organisation=user.agent.organisation )

           

        return queryset


class CategoryDetailView(LoginRequiredMixin,generic.DetailView):
    template_name="leads/category_detail.html"
    context_object_name="category"


    def get_queryset(self):
        user=self.request.user

        if user.is_organisor:
            queryset=Category.objects.filter(organisation=user.userprofile )

        else:
            queryset=Category.objects.filter(organisation=user.agent.organisation )

           

        return queryset
    
   
    
    def get_context_data(self, **kwargs):
        context= super(CategoryDetailView,self).get_context_data(**kwargs)
        
        # qs=Lead.objects.filter(category=self.get_object())
        #both of these do the same thing
        
        leads=self.get_object().leads.all()

        

        context.update({
            "leads":leads
        })

        return context

class LeadCategoryUpdateView(LoginRequiredMixin,generic.UpdateView):

    template_name="leads/lead_category_update.html"
    form_class=LeadCategoryUpdateForm
    
    
    context_object_name="lead"

    

    def get_success_url(self):
        return reverse("leads:lead_view" , kwargs={"pk":self.get_object().id})


    def get_queryset(self):
            user=self.request.user

            if user.is_organisor:
                queryset=Lead.objects.filter(organisation=user.userprofile)

            elif user.is_agent:
                queryset=Lead.objects.filter(organisation=user.agent.organisation)

                #filter for the agent that is logged in
                queryset=queryset.filter(agent__user=user)

            return queryset
    






# def lead_update(request,pk):
#     form=LeadForm()
#     lead=Lead.objects.get(id=pk)
#     if request.method=="POST":
        
#         form=LeadForm(request.POST)
#         if form.is_valid():
#             first_name=form.cleaned_data['first_name']
#             last_name=form.cleaned_data['last_name']
#             age=form.cleaned_data['age']
            
#             lead.first_name=first_name
#             lead.last_name=last_name
#             lead.age=age
#             lead.save()

#             return redirect("/leads")
            
            
#     # if request.method=="POST":
#     context={
#         'lead':lead,
#         'form':form
#         }
    
#     return render(request,"leads/lead_update.html",context)




# def lead_create(request):
#     form=LeadForm()
    
    # if request.method=="POST":
    #     print("recieving post request")
    #     form=LeadForm(request.POST)
    #     if form.is_valid():
    #         print("the form is valid")
    #         print(form.cleaned_data)
    #         first_name=form.cleaned_data['first_name']
    #         last_name=form.cleaned_data['last_name']
    #         age=form.cleaned_data['age']
    #         agent=Agent.objects.first()
    #         Lead.objects.create(
    #             first_name=first_name,
    #             last_name=last_name,
    #             age=age,
    #             agent=agent
    #         )
    #         return redirect("/leads")

leads/templates/leads/assign_agent.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

  <a href="{% url 'leads:lead_list' %}">go back to the leads page</a>
  <hr/>
    <h1>assign agent to this lead</h1>    
    <form method="post" >

        {% csrf_token %}
        {{form|crispy}}
        <button type="submit">submit</button>
    </form>
    
    {% endblock content %}

leads/templates/leads/category_list.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-col text-center w-full mb-20">
        <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Categories</h1>
        <p class="lg:w-2/3 mx-auto leading-relaxed text-base">these categories segment the leads</p>
      </div>
      <div class="lg:w-2/3 w-full mx-auto overflow-auto">
        <table class="table-auto w-full text-left whitespace-no-wrap">
          <thead>
            <tr>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">name</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">lead count</th>
              
            </tr>
          </thead>
          <tbody>
            <tr>
                <td class="px-4 py-3"> unassigned lead</td>
                <td class="px-4 py-3">{{unassigned_lead_count}}</td>
            </tr>

            
                {% for category in category_list %}
                <tr>
                    <td class="px-4 py-3"><a href="{% url 'leads:category_detail' category.pk %}">{{category.name}}</a></td>
                    <td class="px-4 py-3">TODO count/s</td>
                </tr>


                {% endfor %}
            
            
          </tbody>
        </table>
      </div>
      
  </section>

{% endblock content %}

leads/templates/leads/lead_category_update.html
{% extends "base.html" %}
{% load tailwind_filters %}


{% block content %}
  
<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{lead.first_name}} {{lead.last_name}}</h1>
          <div class="flex mb-4">
            <a href="{% url 'leads:lead_view' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Overview</a>
            <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Category</a>
            <a href="{% url 'leads:lead_update' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Category Update</a>
          </div>
  
          <form method="post" id="changevaluesubmit">
  
            {% csrf_token %}
            {{form|crispy}}
            
        </form>
          
          <div class="flex">
            
            <button type="submit" form="changevaluesubmit" class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Submit</button>
            
          </div>
        </div>
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
      </div>
    </div>
  </section>
  
    <a href="{% url 'leads:lead_list' %}">go back to the leads page</a>
    <hr/>
{% endblock content %}

leads/templates/leads/lead_create.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

  <a href="{% url 'leads:lead_list' %}">go back to the leads page</a>
  <hr/>
    <h1>create a new lead</h1>    
    <form method="post" >

        {% csrf_token %}
        {{form|crispy}}
        <button class="hover:text-blue-500 mt-3" type="submit">submit</button>
    </form>
    
    {% endblock content %}

leads/templates/leads/lead_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

  <a href="{% url 'leads:lead_list' %}">go back to the leads page</a>
  <hr/>
    <h1>delete the lead</h1>    
    <form method="post" >

        {% csrf_token %}
        {{form|crispy}}
        <button type="submit">submit</button>
    </form>
    
    {% endblock content %}

{% comment %} i guess lead delete view uses the form by default so thats why it is used here {% endcomment %}

leads/templates/leads/lead_details.html
{% extends "base.html" %}

{% block content %}


<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <a href="{% url 'leads:lead_list' %}" ><h2 class="text-sm title-font text-gray-500 tracking-widest hover:text-red-900">LEAD</h2></a>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{leads.first_name}} {{leads.last_name}}</h1>
          <div class="flex mb-4">
            <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Overview</a>
            <a href="{% url 'leads:lead_category_update' leads.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Category</a>
            <a href="{% url 'leads:lead_update' leads.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Lead Update</a>
          </div>
          <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Age</span>
            <span class="ml-auto text-gray-900">{{leads.age}}</span>
          </div>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">location</span>
            <span class="ml-auto text-gray-900">dummy location</span>
          </div>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">phone no</span>
            <span class="ml-auto text-gray-900">456464545</span>
          </div>
          <div class="flex border-t border-b mb-6 border-gray-200 py-2">
            <span class="text-gray-500">agent</span>
            <span class="ml-auto text-gray-900">{{leads.agent}}</span>
          </div>
          <div class="flex">
            
            <a href='/leads/{{ leads.pk }}/delete/' class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">delete</a>
            
          </div>
        </div>
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
      </div>
    </div>
  </section>




    {% endblock content %}

leads/templates/leads/lead_list.html
{% extends "base.html" %}

{% block content %}



<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
      <div>
        <h1 class="text-4xl text-gray-800"> Leads</h1>

      </div>
      <div>
        <a class="text-gray-500 hover:text-blue-500"href="{% url 'leads:category_list' %}"> view categories</a>
      </div>
      {% if request.user.is_organisor  %}
      <div>
        <a class="text-gray-500 hover:text-blue-500"href="{% url 'leads:lead_create' %}"> Create a new lead</a>
      </div>
      {% endif %}
    </div>
    <div class="flex flex-wrap -m-4">
      {% for leadn in lead %}
      <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24" data-darkreader-inline-stroke="" style="--darkreader-inline-stroke: currentColor;">
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{leadn.first_name}} {{leadn.last_name}}</h2>
            <p class="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.</p>
            <a href="{% url 'leads:lead_view' leadn.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">view this lead
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24" data-darkreader-inline-stroke="" style="--darkreader-inline-stroke: currentColor;">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
          
        </div>
      </div>
      {% endfor %} 
      <!-- <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10" viewBox="0 0 24 24" data-darkreader-inline-stroke="" style="--darkreader-inline-stroke: currentColor;">
              <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
              <circle cx="12" cy="7" r="4"></circle>
            </svg>
          </div> -->
          
        </div>
      </div>
    </div>
  </div>
</section>

{% if unassigned_lead.exists %}
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
      <div>
        <h1 class="text-4xl text-gray-800"> unassigned  Leads</h1>

      </div>
      
    </div>
    <div class="flex flex-wrap -m-4">
      {% for leadn in unassigned_lead %}
      <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24" data-darkreader-inline-stroke="" style="--darkreader-inline-stroke: currentColor;">
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{leadn.first_name}} {{leadn.last_name}}</h2>
            <p class="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.</p>
            <a href="{% url 'leads:assign_agent' leadn.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">view this lead
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24" data-darkreader-inline-stroke="" style="--darkreader-inline-stroke: currentColor;">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
          
        </div>
      </div>
      {% endfor %} 
      
          
        </div>
      </div>
    </div>
  </div>
</section>
  

{% endif %}

    <h1>these are all the leads</h1>    
    {% for leadn in lead %}

      <div class="lead">
      <a href="{% url 'leads:lead_view' leadn.pk %}"> {{ leadn.first_name }} {{ leadn.last_name }}</a>  Age:{{ leadn.age }}
      </div>

    {% endfor %} 
    <hr/>
    <a href="{% url 'leads:lead_create' %}"> create a new lead </a>


 {% endblock content %}