agents/urls.py
from django.urls import path
from .views import AgentListView,AgentCreateView,AgentDetailView,AgentUpdateView,AgentDeleteView

app_name='agent'

urlpatterns=[

    path('',AgentListView.as_view(),name="agent_list"),
    path('create/',AgentCreateView.as_view(),name="agent_create"),
    path('<int:pk>/',AgentDetailView.as_view(),name="agent_view"),
    path('<int:pk>/update/',AgentUpdateView.as_view(),name="agent_update"),
    path('<int:pk>/delete/',AgentDeleteView.as_view(),name="agent_delete")
]

djcrm/urls.py
from django.contrib import admin
from django.urls import path,include 
from leads.views import landing_page ,landingpageview,SignupView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('leads/',include('leads.urls',namespace="leads")),
    path('agents/',include('agents.urls',namespace="agents")),
    path('',landingpageview.as_view(),name="landing_page"),
    path('reset-password/',PasswordResetView.as_view(),name="reset-password"),
    path('password-reset-done/',PasswordResetDoneView.as_view(),name="password_reset_done"),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(),name="password_reset_complete"),
    path('password-reset-confirm/<uidb64>/<token>/',PasswordResetConfirmView.as_view(),name="password-reset-confirm"),
    path('login/',LoginView.as_view(),name="login"),
    path('logout/',LogoutView.as_view(),name="logout"),
    path('signup/' , SignupView.as_view(),name="signup")
    
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django import forms 
from django.contrib.auth import get_user_model

User=get_user_model()

class AgentModelForm(forms.ModelForm):
    class Meta:
        model=User
        fields=(
            'email',
            'username',
            'first_name',
            'last_name',
        )

agents/views.py
import random
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from leads.models import Agent
from django.shortcuts import reverse
from .forms import AgentModelForm
from.mixins import organisorandLoginRequiredMixin
from  django.core.mail import send_mail


# Create your views here.


class AgentListView(organisorandLoginRequiredMixin,generic.ListView):

    template_name='agents/agent_list.html'


    def get_queryset(self):
        organization= self.request.user.userprofile
        return Agent.objects.filter(organisation=organization)
    
class AgentCreateView(organisorandLoginRequiredMixin,generic.CreateView):
    template_name="agents/agent_create.html"

    form_class=AgentModelForm

    def get_success_url(self):

        return  reverse("agents:agent_list")
    
    def form_valid(self,form):

        user=form.save(commit=False)
        user.is_agent=True
        user.is_organisor=False
        user.set_password(f"{random.randint(0,1000000)}")
        user.save()
        Agent.objects.create(
            user=user,
            organisation=self.request.user.userprofile,
            
        )

        send_mail(
            subject="youu were invited to be an agent",
            message="ypu werer added as  a agent in the django crm please login",
            from_email="admin@test.com",
            recipient_list=[user.email],

        )
        return super(AgentCreateView,self).form_valid(form)


class AgentDetailView(organisorandLoginRequiredMixin,generic.DetailView):

    template_name="agents/agent_detail.html"
    context_object_name="agent"

    def get_queryset(self):
        organization= self.request.user.userprofile
        return Agent.objects.filter(organisation=organization)

class AgentUpdateView(organisorandLoginRequiredMixin,generic.UpdateView):
    template_name="agents/agent_update.html"
    form_class=AgentModelForm
    

    def get_success_url(self):
        return reverse("agents:agent_list")
    
    def get_queryset(self):
        organization= self.request.user.userprofile
        return Agent.objects.filter(organisation=organization)
    
class AgentDeleteView(organisorandLoginRequiredMixin,generic.DeleteView):
    template_name="agents/agent_delete.html"

    def get_success_url(self):
        return reverse("agents:agent_list")
    
    def get_queryset(self):
        organization= self.request.user.userprofile
        return Agent.objects.filter(organisation=organization)
    

agents/templates/agents/agent_create.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

  <a href="{% url 'agents:agent_list' %}">go back to the agents page</a>
  <hr/>
    <h1>create a new agent</h1>    
    <form method="post" >

        {% csrf_token %}
        {{form|crispy}
        <button type="submit">submit</button>
    </form>
    
    {% endblock content %}

agents/templates/agents/agent_delete.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}

<h1>Delete the Agent</h1>

<hr>

<a href="{% url 'agents:agent_list' %}"><h2>go back to agent list</h2></a>


<form  method="post">
    {% csrf_token %}
    {{form|crispy}}

    <button type="submit">
        delete
    </button>

</form>

{% endblock content %}

agents/templates/agents/agent_detail.html
{% extends "base.html" %}

{% block content %}


<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <a href="{% url 'agents:agent_list' %}" ><h2 class="text-sm title-font text-gray-500 tracking-widest hover:text-red-900">AGENT</h2></a>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{agent.user.username}} </h1>
          <div class="flex mb-4">
            <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Overview</a>
            <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Reviews</a>
            <a href="{% url 'agents:agent_update' agent.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Lead Update</a>
          </div>
          <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Age</span>
            <span class="ml-auto text-gray-900">{{leads.age}}</span>
          </div>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">location</span>
            <span class="ml-auto text-gray-900">dummy location</span>
          </div>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">phone no</span>
            <span class="ml-auto text-gray-900">456464545</span>
          </div>
          <div class="flex border-t border-b mb-6 border-gray-200 py-2">
            <span class="text-gray-500">agent</span>
            <span class="ml-auto text-gray-900">{{leads.agent}}</span>
          </div>
          <div class="flex">
            
            <a href='{% url "agents:agent_delete" agent.pk %}' class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">delete</a>
            
          </div>
        </div>
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
      </div>
    </div>
  </section>




    {% endblock content %}

agents/templates/agents/agent_list.html
{% extends "base.html" %}

{% block content %}



<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
      <div>
        <h1 class="text-4xl text-gray-800"> Agents</h1>

      </div>
      <div>
        <a class="text-gray-500 hover:text-blue-500"href="{% url 'agents:agent_create' %}"> Create a new agent</a>
      </div>
    </div>
    <div class="flex flex-wrap -m-4">
      {% for agent in object_list %}
      <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24" data-darkreader-inline-stroke="" style="--darkreader-inline-stroke: currentColor;">
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{agent.user.username}}</h2>
            <p class="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.</p>
            <a href="{% url 'agents:agent_view' agent.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">view this lead
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24" data-darkreader-inline-stroke="" style="--darkreader-inline-stroke: currentColor;">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
          
        </div>
      </div>
      {% endfor %} 
      <!-- <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10" viewBox="0 0 24 24" data-darkreader-inline-stroke="" style="--darkreader-inline-stroke: currentColor;">
              <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
              <circle cx="12" cy="7" r="4"></circle>
            </svg>
          </div> -->
          
        </div>
      </div>
    </div>
  </div>
</section>

 


 {% endblock content %}

agents/templates/agents/agent_update.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENT</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{agent.user.username}} </h1>
        <div class="flex mb-4">
          <a href="{% url 'agents:agent_view' agent.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Overview</a>
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Reviews</a>
          <a href="{% url 'agents:agent_update' agent.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Lead Update</a>
        </div>

        <form method="post" id="changevaluesubmit">

          {% csrf_token %}
          {{form.as_p}}
          
      </form>
        
        <div class="flex">
          
          <button type="submit" form="changevaluesubmit" class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Submit</button>
          
        </div>
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>

  <a href="{% url 'agents:agent_list' %}">go back to the agent page</a>
  <hr/>
    
    
    {% endblock content %}