agents/urls.py
from django.urls import path
from .views import AgentListView,AgentCreateView,AgentDetailView,AgentUpdateView,AgentDeleteView

app_name='agent'

urlpatterns=[

    path('',AgentListView.as_view(),name="agent_list"),
    path('create/',AgentCreateView.as_view(),name="agent_create"),
    path('<int:pk>/',AgentDetailView.as_view(),name="agent_view"),
    path('<int:pk>/update/',AgentUpdateView.as_view(),name="agent_update"),
    path('<int:pk>/delete/',AgentDeleteView.as_view(),name="agent_delete")
]

djcrm/urls.py
from django.contrib import admin
from django.urls import path,include 
from leads.views import landing_page ,landingpageview,SignupView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('leads/',include('leads.urls',namespace="leads")),
    path('agents/',include('agents.urls',namespace="agents")),
    path('',landingpageview.as_view(),name="landing_page"),
    path('reset-password/',PasswordResetView.as_view(),name="reset-password"),
    path('password-reset-done/',PasswordResetDoneView.as_view(),name="password_reset_done"),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(),name="password_reset_complete"),
    path('password-reset-confirm/<uidb64>/<token>/',PasswordResetConfirmView.as_view(),name="password-reset-confirm"),
    path('login/',LoginView.as_view(),name="login"),
    path('logout/',LogoutView.as_view(),name="logout"),
    path('signup/' , SignupView.as_view(),name="signup")
    
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path

from .views import (LeadListView,LeadDetailView,LeadCreateView,
                    LeadUpdateView,DeleteView,AssignAgentView,
                    CategoryListView,CategoryDetailView,LeadCategoryUpdateView)

app_name="leads"

urlpatterns=[
    path('',LeadListView.as_view(),name="lead_list"),
    path('<int:pk>/',LeadDetailView.as_view(),name="lead_view"),
    path('<int:pk>/update/',LeadUpdateView.as_view(),name="lead_update"),
    path('<int:pk>/delete/',DeleteView.as_view(),name="lead_delete"),
    path('create/',LeadCreateView.as_view(),name="lead_create"),
    path('<int:pk>/assign-agent/',AssignAgentView.as_view(),name="assign_agent"),
    path('<int:pk>/category/',LeadCategoryUpdateView.as_view(),name="lead_category_update"),
    path('categories/',CategoryListView.as_view(),name="category_list"),
    path('categories/<int:pk>/',CategoryDetailView.as_view(),name="category_detail")
    

]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DJCRM</title>
    <script src="https://unpkg.com/@tailwindcss/browser@4"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    <div class="max-w-7xl mx-auto ">
    {% include "navbar.html" %}
    {% block content %}
    {% endblock content %}
    </div>
    

    {% include "scripts.html" %}
    
</body>
</html>

templates/navbar.html
<header class="text-gray-600 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24" data-darkreader-inline-stroke="" style="--darkreader-inline-stroke: currentColor;">
        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg>
      <span class="ml-3 text-xl">DJANGO CRM</span>
    </a>
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      <!-- <a class="mr-5 hover:text-gray-900">First Link</a>
      <a class="mr-5 hover:text-gray-900">Second Link</a> -->
      
      {% if not request.user.is_authenticated %}
      <a href="{% url 'signup' %}" class="mr-5 hover:text-gray-900">Sign up</a>
      {% else %}
        <a href="{% url 'leads:lead_list' %}" class="mr-5 hover:text-gray-900">leads</a>
        {% if request.user.is_organisor %}
        <a href="{% url 'agents:agent_list' %}" class="mr-5 hover:text-gray-900">agent</a>
        {% endif %}
      {% endif %}
    </nav>
    {% if request.user.is_authenticated %}
         logged in as:{{ request.user.username }}
         <form action='{% url "logout" %}' method="post">
          {% csrf_token %}
        <!-- <a href='{% url "logout" %}' type="submit" class=" ml-3 inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Logout
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24" data-darkreader-inline-stroke="" style="--darkreader-inline-stroke: currentColor;">
            <path d="M5 12h14M12 5l7 7-7 7"></path>
          </svg>
        </a> -->
        <button class=" ml-3 inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0" type="submit">Logout 
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24" data-darkreader-inline-stroke="" style="--darkreader-inline-stroke: currentColor;">
              <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
      </button>
      </form>
      {% else %}
    <a href='{% url "login" %}' class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Login
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24" data-darkreader-inline-stroke="" style="--darkreader-inline-stroke: currentColor;">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </a>
    {% endif %}
  </div>
</header>

templates/scripts.html
{% load static %}


<script src="{% static 'main.js' %}">
    
</script>

templates/second_page.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>HTML 5 Boilerplate</title>
    
  </head>
  <body>
    <h1>this the motherfucking second page in which the intellisense also just doesn;t fucking wors</h1>
    {{lead}}

    <ul>
        {% for leadn in lead %}
        <li>{{leadn}}</li>
        {% endfor %}
    </ul>
    
  </body>
</html>